### PR TITLE
Refactor for easier contribution and fix many other issues

### PR DESCRIPTION
**Pull request by Spittal**
# Spittal's 2020 Refactor
to make `vue-i18n-extract` easier to contribute to in 2020.

Should be completely backwards compatible with earlier versions of `vue-i18n-extract`

### What's new?

- Removed `@pika/pkg`, which doesn't have much use or uptake in the community, replaced with https://github.com/developit/microbundle
- Removed `yargs` in favour of using `commander.js`, which has less dependancies and a more terse syntax https://github.com/tj/commander.js/
- Moved to Yarn 2 (berry) for package management https://dev.to/arcanis/introducing-yarn-2-4eh1
- Removed `cli-table3` and replaced with NodeJs native `console.table` function
- Moved away from a class based API, this helps with tree shaking if users want to use `vue-i18n-exract` in their own projects
- Changed the file structure to reflect commands, which is a little more standard in the NodeJS community and makes it easier to understand what file does what.
- Moved from `tslint` to `eslint` as recommended by the Typescript team
- Removed several unused modules
- Small code changes to help with readability and to conform to Typescript standards (no more use of `any`)
- Updated Docs for readability
- Now uses native `bin` functionality of NPM.

### What's Left?

- [x] Refactor Tests
- [x] Rewrite docs to reflect the new changes where needed
- [x] Update CircleCI to build the new package

### CODE REVIEW

**Comment by Spittal** [comment]
Hey @pixari , I'm have finished my refactor and am very happy with it! I even added some new features arround the `-add` function. It should work with language files in JSON, JS, and Yaml now! 🎉 

If you could take a look at the changes that would be great! Then we can merge it to master!

**Comment by Spittal** [comment]
Fixes #57

**Comment by pixari** [comment]
Hi @Spittal!

Nice work. It will take some time to review it and I am very, very glad to do it!

Thank you for telling me about Yarn2, I was not aware of it.

**Comment by Spittal** [comment]
Hi @pixari any movement on getting this merged? I plan to make some changes with some repos that depend on this code.

**Pull request merged**
