### PR TITLE
Added an option to override the DotObject separator (fix merge conflicts and update code)

### PR DESCRIPTION
**Pull request by vricosti**
I have resumed the existing PR by fixing merge conflicts and updated code.
I have tested and when separator option is not given it works as the original and when separator is given (tested with  @) it works as expected and do not created nested strings.

### CODE REVIEW

**Comment by Spittal** [comment]
Hey this is looking great! We're gonna merge https://github.com/pixari/vue-i18n-extract/pull/124 shortly which changes the code up a bit, might be worth editing the code to conform to that as it's going to be the main release moving forward

**Comment by pixari** [comment]
Hi @vricosti!
We merged #124.
Could you please solve the conflicts?
As soon as the conflicts will be solved, we will merge this PR.

Thank you very much! 🙏

**Comment by vricosti** [comment]
> Hi @vricosti!
> We merged #124.
> Could you please solve the conflicts?
> As soon as the conflicts will be solved, we will merge this PR.
> 
> Thank you very much! 🙏

Ok I will try

**Comment by Spittal** [comment]
Closing due to https://github.com/pixari/vue-i18n-extract/pull/134 being merged

**Pull request closed without merging**
